### ISSUE TITLE
What I think about your code/question

### ISSUE THREAD

**Issue by Rafkev** [Soldan3/question#1]
1) For normal or custom billing and shipping fields you can use woocommerce_billing_fields or woocommerce_shipping_fields action hooks on checkout page as follow.

It will make a custom checkout field required without any need to add a validation script and to save it in the order. The field will also appear in My account edit adresses field section.

Some argument explanations:

The class 'update_totals_on_change' allow to trigger "update checkout" on change.
The 'required' attribute make the field required or not
The 'priority' attribute allow you to change the location of the field.

Use this code snippet in your funtion.php 

add_filter( 'woocommerce_shipping_fields', 'display_shipping_region_checkout_field', 20, 1 );
function display_shipping_region_checkout_field( $fields ) {
    $fields['shipping_region'] = array(
        'type'        => 'select',
        'label'       => __("Region", "woocommerce") ,
        'class'       => array('form-row-wide', 'update_totals_on_change'),
        'required'    => true,
        'options'       => array(
            ''         => __("Choose a region please"),
            'option-1' => __("Option 01"),
            'option-2' => __("Option 02"),
            'option-3' => __("Option 03"),
        ),
        'priority' => 100, 
        'clear' => true,
    );
    return $fields;
}

**Comment by Soldan3** [comment]
Thank you man for the clear explanation, but I am new to WordPress, where is the function.php file?

**Comment by Soldan3** [comment]
Okay, thank you. Raphael.

**Comment by Rafkev** [comment]
Cheers!

**Comment by Rafkev** [comment]
Great! Kindly let me know if you need help again.
